name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile tmdparse
      run: cc tmdparse.c -o tmdparse
    - name: Compile tikdecrypt
      run: cc tikdecrypt.c crypto/aes.c -o tikdecrypt
    - name: Download, decrypt and verify IOS9
      run: ./nus_download.sh 0000000100000009
    - name: Download, decrypt and verify System Menu
      run: ./nus_download.sh 0000000100000002
    - name: Download, decrypt and verify Internet Channel
      run: ./nus_download.sh 0001000148414450